# General description:
#    This common.mk contains usefull rules for the project compilation. It's
# design to be reused in diffetent paths, with recursive make invocations.
# 
# Variables needed:
#    To work correctly two main variables are needed:
#       -> TARGET_DIR: This variable defines the location where all the
#                      generated files should go. If this variable is not
#                      setted, then a error is reported and make will stop.
#       -> SRC_DIR: This variable defines the path where all the sources are
#                   located. If this variable is not setted, make won't be
#                   able to find any source, and consecuently won't compile
#                   any binary; anyway, the funtions and rules define in this
#                   will be available.
# 
# Variables used:
#    There are internal variables created, available to be used in parent
# makefile to control the build process:
#       -> SOURCES: This variable contains the path, separated by spaces, of all
#                   the sources find in SRC_DIR directory and it's
#                   subdirectories. 
#       -> OBJECTS: This variable contains the name, and path, of the object
#                   files to be created. Each source file will generate an object
#                   file in the TARGET_DIR, with same relative path.
#       -> TARGET_LINK: To avoid using absolute path this variable is created
#                       with the name of the TARGET_DIR. So, if TARGET_DIR is not
#                       located in CURDIR a link named TARGET_LINK is created.
#       -> TARGET_DIRS: This variable contain the paths, separated by spaces, of
#                       all OBJECTS. It's used to create needed the directory
#                       tree in the TARGET_DIR to avoid compilation errors
#                       (caused by missing directories).
#       -> post_build: This is a PHONY target used to delete the unneeded
#                      TARGET_LINK, before terminate make execution. This target
#                      must be executed at last.
#                      THIS TARGET MUST BE USED IN PARENTS MAKEFILE.
# 

ifndef TARGET_DIR
	$(error TARGET_DIR is not set)
endif
.SUFFIXES: .c .o .h .mk
.PHONY: post_build
#################################################################################
#################### FUNCTIONS:
define getObjFileNameFromSrc
$(addprefix $(TARGET_LINK)/, $(patsubst %.c, %.o, $1))
endef
#################################################################################
#################### COMPILATION AUTOGENERATED VARIABLES:
SOURCES       = $(shell find "$(SRC_DIR)" -name "*.c";)
OBJECTS       = $(call getObjFileNameFromSrc,$(SOURCES))
TARGET_LINK   = $(notdir $(TARGET_DIR))
TARGET_DIRS   = $(sort $(dir $(OBJECTS)))

-include $(OBJECTS:.o=.mk)
post_build:
	rm $(TARGET_LINK)
#################################################################################
#################### STATIC PATTERN RULES:
$(TARGET_LINK)/%.o: %.c | $(TARGET_DIRS)
	$(COMPILE.c) -MM $< -MT $@ -MF $(@:.o=.mk)
	$(COMPILE.c) -o $@ $<
#################################################################################
#################### DIRECTORY GENERATION RULES:
$(TARGET_DIRS): %: | $(TARGET_LINK)
	mkdir -p $@

$(TARGET_LINK):
	ln -s "$(TARGET_DIR)" $@
